global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'bore-monitor'

scrape_configs:
  - job_name: 'bore-backend'
    static_configs:
      - targets: ['backend:3000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
