---
apiVersion: v1
kind: Service
metadata:
  name: bore-backend-debug
  labels:
    app.kubernetes.io/name: bore
    app.kubernetes.io/component: backend
    environment: development
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: bore
    app.kubernetes.io/component: backend

---
apiVersion: v1
kind: Service
metadata:
  name: bore-server-debug
  labels:
    app.kubernetes.io/name: bore
    app.kubernetes.io/component: bore-server
    environment: development
spec:
  type: LoadBalancer
  ports:
  - port: 7835
    targetPort: 7835
    protocol: TCP
    name: tunnel
  selector:
    app.kubernetes.io/name: bore
    app.kubernetes.io/component: bore-server

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-debug
  labels:
    app.kubernetes.io/name: bore
    app.kubernetes.io/component: postgres
    environment: development
spec:
  type: LoadBalancer
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app.kubernetes.io/name: bore
    app.kubernetes.io/component: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: redis-debug
  labels:
    app.kubernetes.io/name: bore
    app.kubernetes.io/component: redis
    environment: development
spec:
  type: LoadBalancer
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app.kubernetes.io/name: bore
    app.kubernetes.io/component: redis