---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bore-backend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: bore-backend-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: bore
      app.kubernetes.io/component: backend